version: "3.9"

services:
  python:
    image: python:3.11-slim
    container_name: python_runner
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["python3"]

  latex:
    image: blang/latex:latest
    container_name: latex_compiler
    volumes:
      - ./:/data
    working_dir: /data
    entrypoint: ["pdflatex"]
