name: Mannual trigger

on:
  workflow_dispatch:

jobs:
  setup-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify installation
        run: docker-compose --version

  run-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PDF Resume
        run: |
          docker-compose run --rm python json_to_latext.py && docker-compose run --rm latex resume.tex

