name: Manual trigger

on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    needs: setup-compose   # <-- ensures this runs after setup-compose
    steps:
      - uses: actions/checkout@v4

      - name: Generate PDF Resume
        run: |
          docker compose run --rm python json_to_latext.py
          docker compose run --rm latex resume.tex
